/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get platform statistics
         * @description Returns aggregate platform statistics for the home page banner. Cached for 60 seconds.
         */
        get: operations["getPlatformStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List markets */
        get: operations["listMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get market by ID */
        get: operations["getMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{market_id}/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bets for a market */
        get: operations["getMarketBets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{market_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregate stats for a market */
        get: operations["getMarketStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bets/{bettor_address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all bets by a Stellar address */
        get: operations["getBetsByAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get portfolio summary for a Stellar address */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oracle/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a signed oracle fight result */
        post: operations["submitOracleResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oracle/reports/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all oracle reports for a fight */
        get: operations["getOracleReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/dispute/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flag a market as disputed */
        post: operations["flagDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/resolve-dispute/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a disputed market with admin-verified outcome */
        post: operations["resolveDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cancel/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a market (fight postponed or called off) */
        post: operations["cancelMarket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Market: {
            id?: number;
            market_id?: string;
            contract_address?: string;
            match_id?: string;
            fighter_a?: string;
            fighter_b?: string;
            weight_class?: string;
            title_fight?: boolean;
            venue?: string;
            /** Format: date-time */
            scheduled_at?: string;
            /** @enum {string} */
            status?: "open" | "locked" | "resolved" | "cancelled" | "disputed";
            /** @enum {string|null} */
            outcome?: "fighter_a" | "fighter_b" | "draw" | "no_contest" | null;
            pool_a?: string;
            pool_b?: string;
            pool_draw?: string;
            total_pool?: string;
            fee_bps?: number;
            /** Format: date-time */
            resolved_at?: string | null;
            /** @enum {string|null} */
            oracle_used?: "primary" | "fallback" | "admin" | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            ledger_sequence?: number;
        };
        MarketStats: {
            market_id?: string;
            total_bets?: number;
            unique_bettors?: number;
            largest_bet_xlm?: number;
            average_bet_xlm?: number;
            total_pooled_xlm?: number;
        };
        PlatformStats: {
            totalMarkets?: number;
            activeMarkets?: number;
            totalVolume?: number;
            totalBets?: number;
        };
        Bet: {
            id?: number;
            market_id?: string;
            bettor_address?: string;
            /** @enum {string} */
            side?: "fighter_a" | "fighter_b" | "draw";
            amount?: string;
            amount_xlm?: number;
            /** Format: date-time */
            placed_at?: string;
            claimed?: boolean;
            /** Format: date-time */
            claimed_at?: string | null;
            payout?: string | null;
            tx_hash?: string;
            ledger_sequence?: number;
        };
        Portfolio: {
            address?: string;
            active_bets?: components["schemas"]["Bet"][];
            past_bets?: components["schemas"]["Bet"][];
            pending_claims?: components["schemas"]["Bet"][];
            total_staked_xlm?: number;
            total_won_xlm?: number;
            total_lost_xlm?: number;
        };
        OracleReport: {
            id?: number;
            match_id?: string;
            oracle_address?: string;
            outcome?: string;
            /** Format: date-time */
            reported_at?: string;
            signature?: string;
            accepted?: boolean;
            tx_hash?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Error: {
            /** @example error */
            status?: string;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlatformStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStats"];
                };
            };
        };
    };
    listMarkets: {
        parameters: {
            query?: {
                status?: "open" | "locked" | "resolved" | "cancelled" | "disputed";
                weight_class?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of markets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        markets?: components["schemas"]["Market"][];
                        total?: number;
                        page?: number;
                        limit?: number;
                    };
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market detail with current odds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMarketBets: {
        parameters: {
            query?: {
                /** @description Filter to a single bettor's Stellar address */
                address?: string;
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bet"][];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMarketStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStats"];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBetsByAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stellar public key (G...) */
                bettor_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bets across all markets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bet"][];
                };
            };
            /** @description Invalid Stellar address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stellar public key (G...) */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio summary (empty portfolio returned if address has no bets) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Invalid Stellar address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitOracleResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    match_id: string;
                    /** @enum {string} */
                    outcome: "fighter_a" | "fighter_b" | "draw" | "no_contest";
                    /** Format: date-time */
                    reported_at: string;
                    /** @description Hex-encoded Ed25519 signature */
                    signature: string;
                    /** @description Stellar public key of the oracle */
                    oracle_address: string;
                };
            };
        };
        responses: {
            /** @description Report accepted and submitted on-chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx_hash?: string;
                        report_id?: number;
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid oracle API key / signature verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOracleReports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All oracle reports (accepted and rejected) for the fight */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OracleReport"][];
                };
            };
        };
    };
    flagDispute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Market flagged as disputed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx_hash?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resolveDispute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    outcome: "fighter_a" | "fighter_b" | "draw" | "no_contest";
                    /** @description 6-digit TOTP code for 2FA verification */
                    totp_code: string;
                };
            };
        };
        responses: {
            /** @description Dispute resolved on-chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx_hash?: string;
                    };
                };
            };
            /** @description Unauthorized or invalid TOTP code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Market cancelled on-chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx_hash?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
